ShopEx01.Web/Controllers/ContactController.cs
using AutoMapper;
using BotDetect.Web.Mvc;
using ShopEx01.Common;
using ShopEx01.Model.Models;
using ShopEx01.Service;
using ShopEx01.Web.Infrastructure.Extensions;
using ShopEx01.Web.Models;
using System.Web.Mvc;

namespace ShopEx01.Web.Controllers
{
    public class ContactController : Controller
    {
        private IContactDetailService _contactDetailService;
        private IFeedbackService _feedbackService;

        public ContactController(IContactDetailService contactDetailService, IFeedbackService feedbackService)
        {
            this._contactDetailService = contactDetailService;
            this._feedbackService = feedbackService;
        }

        // GET: Contact
        public ActionResult Index()
        {
            FeedbackViewModel viewModel = new FeedbackViewModel();
            viewModel.ContactDetail = GetDetail();
            return View(viewModel);
        }

        [HttpPost]
        [CaptchaValidation("CaptchaCode", "contactCaptcha", "Mã xác nhận không đúng")]
        public ActionResult SendFeedback(FeedbackViewModel feedbackViewModel)
        {
            if (ModelState.IsValid)
            {
                Feedback newFeedback = new Feedback();
                newFeedback.UpdateFeedback(feedbackViewModel);
                _feedbackService.Create(newFeedback);
                _feedbackService.Save();

                ViewData["SuccessMsg"] = "Gửi phản hồi thành công";

                string content = System.IO.File.ReadAllText(Server.MapPath("/Assets/client/template/contact_template.html"));
                content = content.Replace("{{Name}}", feedbackViewModel.Name);
                content = content.Replace("{{Email}}", feedbackViewModel.Email);
                content = content.Replace("{{Message}}", feedbackViewModel.Message);
                var adminEmail = ConfigHelper.GetByKey("AdminEmail");
                MailHelper.SendMail(adminEmail, "Thông tin liên hệ từ website", content);

                feedbackViewModel.Name = "";
                feedbackViewModel.Message = "";
                feedbackViewModel.Email = "";
            }
            feedbackViewModel.ContactDetail = GetDetail();
            MvcCaptcha.ResetCaptcha("contactCaptcha");
            return View("Index", feedbackViewModel);
        }

        private ContactDetailViewModel GetDetail()
        {
            var model = _contactDetailService.GetDefaultContact();
            var contactViewModel = Mapper.Map<ContactDetail, ContactDetailViewModel>(model);
            return contactViewModel;
        }
    }
}

ShopEx01.Web/Views/Contact/Index.cshtml
@model ShopEx01.Web.Models.FeedbackViewModel
@using BotDetect.Web.Mvc;


@{
    ViewBag.Title = "Liên hệ";
    Layout = "~/Views/Shared/Layouts.cshtml";
}
@section footerJS{
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyATkx-fEPKCeMkEPeHIr4jZXWmeFeNJZi0"></script>
    <script src="~/Assets/client/js/controllers/contact.js"></script>
}
<style>
    #map {
        height: 500px;
    }
</style>
<link href="@BotDetect.Web.CaptchaUrls.Absolute.LayoutStyleSheetUrl" rel="stylesheet" type="text/css" />
<input type="hidden" id="hidAddress" value="@Model.ContactDetail.Name<br />Điện thoại:@Model.ContactDetail.Phone <br>Địa chỉ: @Model.ContactDetail.Address" />
<input type="hidden" id="hidLat" value="@Model.ContactDetail.Lat" />
<input type="hidden" id="hidLat" value="@Model.ContactDetail.Lat" />
<input type="hidden" id="hidLng" value="@Model.ContactDetail.Lng" />
<input type="hidden" id="hidName" value="@Model.ContactDetail.Name" />

<div id="contact-page" class="container">
    <div class="bg">
        <div class="row">
            <div class="col-sm-9">
                <h2></h2>
                <h2 class="title text-center">Liên hệ <strong>Shop</strong></h2>
                <div id="map" class="contact">
                </div>
            </div>
            <div class="col-sm-9">
                <div class="contact-info">
                    <h2></h2>
                    <h2 class="title text-center">Thông tin liên hệ</h2>
                    <address class="title text-center">
                        <p>E-Shopper Inc.</p>
                        <p> @Model.ContactDetail.Address </p>
                        <p>Tp.Ho Chi Minh</p>
                        <p>SĐT: @Model.ContactDetail.Phone</p>
                        <p>Email: &nbsp; <a href="mailto:@(Model.ContactDetail.Email)"> @Model.ContactDetail.Email</a> </p>
                    </address>
                    <div class="social-networks">
                        <h2></h2>
                        <h2 class="title text-center">Mạng xã hội</h2>
                        <ul>
                            <li>
                                <a href="#"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-google-plus"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-youtube"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-9">
                <div class="contact-form">
                    <h2></h2>
                    <h2 class="title text-center">Gửi thông tin liên hệ</h2>
                    @using (Html.BeginForm("SendFeedback", "Contact", FormMethod.Post))
                    {
                        if (ViewData["SuccessMsg"] != null)
                        {
                            <div class="alert alert-success" role="alert">
                                <strong>Chúc mừng bạn! </strong> gửi phản hồi thành công.
                                <br />Chúng tôi sẽ liên hệ lại sớm nhất có thể.
                            </div>
                        }
                        @Html.ValidationSummary(false, "", new { @class = "error" });
                        <p>Tên của bạn:</p>
                        @Html.TextBoxFor(model => model.Name, new { @class = "textbox" });
                        <p>Email của bạn:</p>
                        @Html.TextBoxFor(model => model.Email, new { @class = "textbox" });
                        <p>Tin nhắn của bạn cho shop:</p>
                        @Html.TextAreaFor(model => model.Message);

                        MvcCaptcha contactCaptcha = new MvcCaptcha("contactCaptcha");
                        @Html.Captcha(contactCaptcha)
                        @Html.TextBox("CaptchaCode")

                        <div class="form-group col-md-12">
                            <input type="submit" name="submit" class="btn btn-primary pull-right" value="Gửi">
                        </div>
                    }
                    @*<div class="status alert alert-success" style="display: none"></div>
                        <form id="main-contact-form" class="contact-form row" name="contact-form" method="post">
                            <div class="form-group col-md-6">
                                <input type="text" name="name" class="form-control" required="required" placeholder="Tên của bạn">
                            </div>
                            <div class="form-group col-md-6">
                                <input type="text" name="email" class="form-control" required="required" placeholder="Email của bạn">
                            </div>
                            <div class="form-group col-md-12">
                                <input type="text" name="subject" class="form-control" required="required" placeholder="Vấn đề phản hồi của bạn">
                            </div>
                            <div class="form-group col-md-12">
                                <textarea name="message" id="message" required="required" class="form-control" rows="8" placeholder="Phản hồi của bạn"></textarea>
                            </div>
                            <div class="form-group col-md-12">
                                <input type="submit" name="submit" class="btn btn-primary pull-right" value="Gửi">
                            </div>
                        </form>*@
                </div>
            </div>

        </div>
    </div>
</div><!--/#contact-page-->